# Generated by Django 4.2.6 on 2023-11-02 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
